flags: {}
packages:
  - 'acquire-game'
  - 'acquire-tcp'
  - 'acquire-server'
  - 'ioautomata'
  - 'pet-store'
  - 'pet-store-backend'

extra-deps:
  - unagi-chan-0.4.0.0
  - MonadPrompt-1.0.0.5
resolver: lts-10.3
