name: acquire-server
synopsis:  Game Server for Acquire
ghc-options: -Wall -fno-warn-orphans

library:
  source-dirs: src
  dependencies:
    - acquire-game
    - acquire-tcp
    - aeson
    - async
    - base
    - ioautomata
    - mtl
    - network
    - random
  exposed-modules:
    - Acquire.Model
    - Acquire.Messages
  default-extensions:
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables

executables:
  server:
    source-dirs:
      - main
    main: server.hs
    dependencies:
      - acquire-tcp
      - acquire-game
      - acquire-server
      - aeson
      - async
      - base
      - bytestring
      - containers
      - http-types
      - ioautomata
      - network
      - random
      - stm
      - text
      - unagi-chan
      - wai
      - wai-middleware-static
      - wai-websockets
      - websockets
      - warp
  mock:
    source-dirs:
      - main
    main: mock.hs
    dependencies:
      - acquire-tcp
      - acquire-game
      - acquire-server
      - aeson
      - async
      - base
      - bytestring
      - containers
      - http-types
      - ioautomata
      - mtl
      - network
      - stm
      - text
      - unagi-chan
      - wai
      - wai-middleware-static
      - wai-websockets
      - websockets
      - warp
    default-extensions:
      - OverloadedStrings
      - RecordWildCards
      - ScopedTypeVariables
  wsclient:
    source-dirs:
      - main
    main: wsclient.hs
    dependencies:
      - acquire-game
      - acquire-tcp
      - acquire-server
      - aeson
      - base
      - bytestring
      - containers
      - ioautomata
      - mtl
      - network
      - text
      - wai-websockets
      - websockets
    default-extensions:
      - OverloadedStrings
      - RecordWildCards
      - ScopedTypeVariables


tests:
  hspec:
    source-dirs:
      - test
    main: Spec.hs
    dependencies:
      - acquire-game
      - acquire-server
      - base
      - containers
      - data-reify
      - hspec
      - hspec-discover
      - ioautomata
      - mtl
      - QuickCheck
      - random
