name: acquire-server
synopsis:  Game Server for Acquire
ghc-options: -Wall -fno-warn-orphans

executables:
  server:
    source-dirs:
      - src
    main: server.hs
    dependencies:
      - acquire-tcp
      - acquire-game
      - aeson
      - async
      - base
      - bytestring
      - containers
      - http-types
      - ioautomata
      - network
      - stm
      - text
      - unagi-chan
      - wai
      - wai-middleware-static
      - wai-websockets
      - websockets
      - warp
    default-extensions:
      - OverloadedStrings
      - RecordWildCards
      - ScopedTypeVariables
  mock:
    source-dirs:
      - src
    main: mock.hs
    dependencies:
      - acquire-tcp
      - acquire-game
      - aeson
      - async
      - base
      - bytestring
      - containers
      - http-types
      - ioautomata
      - mtl
      - network
      - stm
      - text
      - unagi-chan
      - wai
      - wai-middleware-static
      - wai-websockets
      - websockets
      - warp
    default-extensions:
      - OverloadedStrings
      - RecordWildCards
      - ScopedTypeVariables
  wsclient:
    source-dirs:
      - src
    main: wsclient.hs
    dependencies:
      - acquire-game
      - acquire-tcp
      - aeson
      - base
      - bytestring
      - containers
      - ioautomata
      - mtl
      - network
      - text
      - wai-websockets
      - websockets
    default-extensions:
      - OverloadedStrings
      - RecordWildCards
      - ScopedTypeVariables
